title: Aashutosh Panchal
author: Aashutosh Panchal
url: "https://aashu-p.github.io"
baseurl: "/aashutosh.github.io"

permalink: /blog/:title/

social:
  linkedin: "https://www.linkedin.com/in/aashutosh-panchal/"
  github: "https://github.com/Aashu-P"
